name = "QEDjl_Registry"
uuid = "8001758d-046d-4e2b-bd0c-65d0e074dbf4"
repo = "git@github.com:QEDjl-project/registry.git"
description = "Local registry for the QEDjl-project."

[packages]
46de9c38-1bb3-4547-a1ec-da24d767fdad = { name = "QEDprocesses", path = "Q/QEDprocesses" }
fc3ce04a-5be5-4f3a-acff-eceaab723759 = { name = "QEDevents", path = "Q/QEDevents" }
