name = "QEDjl_Registry"
uuid = "8001758d-046d-4e2b-bd0c-65d0e074dbf4"
repo = "git@github.com:QEDjl-project/registry.git"
description = "Local registry for the QEDjl-project."

[packages]
35dc0263-cb5f-4c33-a114-1d7f54ab753e = { name = "QEDcore", path = "Q/QEDcore" }
46de9c38-1bb3-4547-a1ec-da24d767fdad = { name = "QEDprocesses", path = "Q/QEDprocesses" }
ac3a6c97-e859-4b9f-96bb-63d2a216042c = { name = "QEDfields", path = "Q/QEDfields" }
bb1fba1d-cf9b-41b3-874e-4b81465537b9 = { name = "QED", path = "Q/QED" }
fc3ce04a-5be5-4f3a-acff-eceaab723759 = { name = "QEDevents", path = "Q/QEDevents" }
